Add collector
yiisoft/router-composer-attribute-collector pull request #1
Opened 2023-10-23 06:52 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌

2023-10-23 17:23 UTC, samdark commented on README.md
> +composer require yiisoft/Router Composer Attribute Composer Collector
```suggestion
composer require yiisoft/router-composer-attribute-collector
```

2023-10-23 17:23 UTC, samdark commented on README.md
> +The package provides a router collector for [Yii Router](https://github.com/yiisoft/router) that collects routes declared through attributes
```suggestion
The package provides a router collector for [Yii Router](https://github.com/yiisoft/router) that collects routes declared through attributes.
```

2023-10-23 17:23 UTC, samdark commented on composer.json
> +        "yiisoft/router": "@dev"
Should point to stable version on release.

2023-11-22 17:21 UTC, vjik requested changes
Tests?

2026-03-29 07:10 UTC, rustamwin commented
> Tests?

Added

2026-03-30 13:20 UTC, merged